# Generated by Django 4.2.2 on 2023-06-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addbook',
            new_name='books',
        ),
    ]
