# Generated by Django 4.2.2 on 2023-06-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteadmin', '0002_rename_addbook_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='bookid',
            new_name='id',
        ),
    ]
