# Generated by Django 4.2.2 on 2023-06-29 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('websiteadmin', '0006_returnbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('memberid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='member',
        ),
    ]
