# Generated by Django 4.2.2 on 2023-06-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteadmin', '0007_members_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='memberid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
