# Generated by Django 4.2.2 on 2023-06-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteadmin', '0008_alter_members_memberid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbooks',
            name='memberid',
            field=models.CharField(max_length=200),
        ),
    ]
