# Generated by Django 4.2.2 on 2023-06-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteadmin', '0009_alter_borrowbooks_memberid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnbook',
            name='memberid',
            field=models.CharField(max_length=200),
        ),
    ]
