# Generated by Django 4.2.2 on 2023-06-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteadmin', '0010_alter_returnbook_memberid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbooks',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowbooks',
            name='member',
        ),
        migrations.RemoveField(
            model_name='borrowbooks',
            name='status',
        ),
        migrations.RemoveField(
            model_name='members',
            name='status',
        ),
    ]
