# Generated by Django 4.2.2 on 2023-07-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteadmin', '0011_remove_borrowbooks_book_remove_borrowbooks_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Bid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
